apiVersion: v1
kind: Service
metadata:
  name: sample-externalip
spec:
  type: ClusterIP
  # ここで指定したIPのPodは
  externalIPs:
  - 10.1.0.158
  - 10.1.0.159
  ports:
  - name: "http-port"
    protocol: "TCP"
    #ClusterIPで受け付けるport番号
    port: 8080
    #転送先コンテナのport番号
    targetPort: 80
  # 転送先のPodを指定(この例の場合はsample-deployment.yamlで作成したpodに)
  selector:
    app: sample-app