apiVersion: v1
kind: Service
metadata:
  name: sample-nodeport
spec:
  type: NodePort
  ports:
  - name: "http-port"
    protocol: "TCP"
    #ClusterIPで受け付けるport番号
    port: 8080
    #転送先コンテナのport番号
    targetPort: 80
    nodePort: 30080
  # 転送先のPodを指定(この例の場合はsample-deployment.yamlで作成したpodに)
  selector:
    app: sample-app