apiVersion: v1
kind: Service
metadata: 
  name: sample-clusterip
spec:
  type: ClusterIP
  # あまり推奨されないがServiceのIPを自動割当ではなく。固定にしたい場合はここに指定
  # clusterIP: 10.11.253.80
  ports:
  - name: "http-port"
    protocol: "TCP"
    #ClusterIPで受け付けるport番号
    port: 8080
    #転送先コンテナのport番号
    targetPort: 80
  # 転送先のPodを指定(この例の場合はsample-deployment.yamlで作成したpodに)
  selector:
    app: sample-app