apiVersion: batch/v1
kind: Job
metadata:
  name: sample-job
spec:
  # completionsとbackoffLimitはor条件でどちらが成立すれば終了
  # 正常終了するPodの数(終了条件)、未指定の場合のデフォルトは無制限。つまり、ワークキューとして動作する
  completions: 1
  # 並列でいくつのPodで作業するか
  parallelism: 1
  # 異常終了するPodの数(終了条件)、未指定の場合のデフォルトは6
  backoffLimit: 10
  template:
    spec: 
      containers:
      - name: sleep-container
        image: centos:latest
        command: ["sleep"]
        args: ["60"]
      # OnFailureまたはNeverが指定可能
      # Never : podに障害が起きた場合、新規のPodを作成
      # OnFailure: 再度同一のPodを利用してJobを再開
      restartPolicy: Never