apiVersion: apps/v1
kind: Deployment
metadata: 
  name: sample-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: sample-app
  # template配下を変更した場合、ReplicaSetを再作成し、ローリングアップデートが行われる
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers: 
      - name: nginx-container
        image: nginx:1.13
        ports:
        - containerPort: 80